[YUNIKORN-1555] Filter out terminated pods during recovery
apache/yunikorn-k8shim pull request #532
Opened 2023-02-15 04:30 UTC by bgrams

### What is this PR for?
Excludes pods in a terminal state (Succeeded, Failed) during scheduler recovery. Applications may otherwise be recovered as "New" and remain there in scenarios where the application has completed and pods are awaiting garbage collection. 

This should not affect recovery behavior for applications with pods in non-terminal states as the application metadata will be recovered according to existing logic.   

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
[YUNIKORN-1555](https://issues.apache.org/jira/browse/YUNIKORN-1555)

### How should this be tested?
e2e

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2023-02-15 10:59 UTC, manirajv06 requested changes
Thanks @bgrams. Yes, we need to ensure this has been covered as part of unit tests. FYI, already there are multiple unit tests available to verify different app recovery scenarios. Also, can we change draft status?

2023-02-15 10:59 UTC, manirajv06 commented on pkg/appmgmt/general/general.go
> +		if utils.GeneralPodFilter(pod) && utils.IsAssignedPod(pod) && !utils.IsPodTerminated(pod) {
Can we use utils#NeedRecovery()?

2023-02-15 14:19 UTC, bgrams commented
> Thanks @bgrams. Yes, we need to ensure this has been covered as part of unit tests. FYI, already there are multiple unit tests available to verify different app recovery scenarios. Also, can we change draft status?

Thanks @manirajv06. I'll update tests to make sure we have coverage. 

I marked this as draft after noticing that we also require changes somewhere in `PodEventHandler#handleEventFromInformers` since there's overlapping recovery logic. Thanks for bearing with me while I figure this one out 😄

2023-02-15 14:23 UTC, bgrams commented on pkg/appmgmt/general/general.go
> +		if utils.GeneralPodFilter(pod) && utils.IsAssignedPod(pod) && !utils.IsPodTerminated(pod) {
Ah yes, perfect

2023-02-23 13:52 UTC, wilfred-s commented
The pod event handler will only be called if there is a new, updated or deleted pod while we are recovering the pods on the  list. The pods events that get cached during the recovery are not processed until after the recovery is done (see `PodEventHandlerRecoveryDone()`). At that point filtering out pod that have finished could mean that you miss a valid event. A pod received as part of the list might be running. While the pod recovery is processing the pod exits and thus goes into a finished state. You need that event to correctly delete the allocation.

2023-02-23 13:53 UTC, wilfred-s requested changes
We need a test for this change too

2023-05-18 21:29 UTC, pbacsko commented
@bgrams do you have any progress with this? We got contacted by another user upstream on Slack who've seen the same issue.

2023-05-20 00:38 UTC, bgrams commented
Hey @pbacsko thanks for the nudge here. I completely forgot about this. Let me take a stab at it this weekend.

2023-05-21 22:48 UTC, bgrams commented on pkg/appmgmt/general/general.go
> +		if utils.GeneralPodFilter(pod) && utils.IsAssignedPod(pod) && !utils.IsPodTerminated(pod) {
Addressed in latest commits

2023-05-22 03:38 UTC, wilfred-s requested changes
Change looks good. One test remark: pod state == Pending will also be recovered if it is assigned and scheduled by YuniKorn. That case is not covered in the test.
Pending could happen if the pod is assigned to the node but has not started all containers yet. The test has 2 running containers on each app. At least 1 container should have a state of pending.
@pbacsko and @craigcondit please correct me if I am wromg

2023-05-22 09:15 UTC, pbacsko commented on pkg/appmgmt/appmgmt_recovery_test.go
> +			"task05": true,
I haven't deeply analized what happens here, but don't we want some variety? In all cases, we expect true, so why do we have this here?

2023-05-22 15:07 UTC, pbacsko commented on pkg/appmgmt/appmgmt_recovery_test.go
> +	pods[5] = newPodHelper("pod6", "task06", "app02", time.Unix(600, 0), v1.PodFailed)
What if we have app03, and task1-4 is PodSucceeded, but task5 (the last one) is PodRunning?
What's the result of that?

2023-05-22 17:01 UTC, closed without merging