[YUNIKORN-1677] move to simple go based web server for e2e tests.
apache/yunikorn-k8shim pull request #568
Opened 2023-04-04 13:28 UTC by zhuqi-lucas

### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2023-04-04 15:27 UTC, craigcondit requested changes
Please put all go code in pkg/webtest/ and pkg/cmd/webtest/ .

2023-04-05 12:17 UTC, zhuqi-lucas commented
Thank you @craigcondit for review, addressed the comments now.

2023-04-05 12:46 UTC, craigcondit requested changes
Minor nit, but we're getting close.

2023-04-05 12:46 UTC, craigcondit commented on deployments/image/webtest/Dockerfile
> +COPY --chown=4444:0 document/index.html /html/
Use `--chown=0:0` here. There's no need to make the content owned by the web user.

2023-04-05 12:57 UTC, craigcondit commented on deployments/image/webtest/Dockerfile
> +COPY --chown=4444:0 document/index.html /html/
Looks good. Will +1 once we get clean e2e runs (may take a while as we've got some test flakiness).

2023-04-05 16:39 UTC, craigcondit approved these changes
+1 LGTM. Single e2e test failure is unrelated.

2023-04-05 16:39 UTC, closed without merging