[YUNIKORN-2695] remove core dependency pkg/common
apache/yunikorn-k8shim pull request #868
Opened 2024-07-02 06:12 UTC by 0lai0

### What is this PR for?
This PR modifies the dependency between yunikorn-k8shim and yunikorn-core. In this PR, the `common.WaitForCondition` method can be called within yunikorn-k8shim, allowing yunikorn-k8shim to function without relying on yunikorn-core. Consequently, this reduces the dependency of YUNIKORN-shim on YUNIKORN-core.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
[[YUNIKORN-2695]](https://issues.apache.org/jira/browse/YUNIKORN-2695)

### How should this be tested?
make test
### Screenshots (if appropriate)

2024-07-02 18:10 UTC, chenyulin0719 requested changes
Test failed, could you please fix it. Thanks.

2024-07-03 03:56 UTC, 0lai0 commented
No problem.I will fix it as soon as possible .

2024-07-03 08:17 UTC, chenyulin0719 commented on pkg/client/clients_test.go
> +	}, 10*time.Millisecond, 5*time.Second)
Do there have any reason to change the timeout to 5 secs?

2024-07-03 12:33 UTC, chenyulin0719 approved these changes
LGTM, The 'preemption' e2e test fail was caused by the known issue in https://issues.apache.org/jira/browse/YUNIKORN-2699

2024-07-04 16:49 UTC, chia7712 approved these changes
LGTM

2024-07-04 16:50 UTC, closed without merging