[YUNIKORN-1126] Added E2E Tests for Best Effort Pod
apache/yunikorn-k8shim pull request #904
Opened 2024-09-03 09:53 UTC by rrajesh-cloudera

This PR is for adding end-to-end tests to verify the scheduling of pods with different Quality of Service (QOS) classes in the YuniKorn Kubernetes scheduler.  The tests are specifically checking the scheduling of pods with "BestEffort" and "NonBestEffort" (likely "Burstable" or "Guaranteed") QOS classes. 
The tests ensure that the pods are correctly scheduled and running and that their QOS classes are as expected.  The PR also includes changes to the SleepPodConfig struct and the InitSleepPod function to support setting the QOS class of the pods.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2714

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2024-09-03 10:29 UTC, ryankert01 commented
Your change doesn't look like 2714 in your jira link, please update that.

2024-09-03 10:44 UTC, rrajesh-cloudera commented
> Your change doesn't look like 2714 in your jira link, please update that.
Updated the Jira in The Description, Copy Paste error. Thanks for Pointing it out!

2024-09-05 10:03 UTC, manirajv06 requested changes

2024-09-05 10:18 UTC, rrajesh-cloudera commented on test/e2e/basic_scheduling/basic_scheduling_test.go
> +
For BestEffortPod we are not setting any resources.

- Guaranteed: A pod where each container has the same requests and limits for CPU and memory.
- Burstable: A pod where one or more containers have resource requests set, but no corresponding limits or they differ.
- BestEffort: A pod where neither resource requests nor limits are set.

2024-09-05 10:34 UTC, rrajesh-cloudera commented on test/e2e/basic_scheduling/basic_scheduling_test.go
> +
Hi @manirajv06  , Updated the code with the latest code. Added assertion for resource allocation and name for both cases.

2024-09-05 10:34 UTC, rrajesh-cloudera commented on test/e2e/basic_scheduling/basic_scheduling_test.go
> +
Added requested assertion to the test

2024-09-05 20:19 UTC, craigcondit approved these changes
+1 LGTM.

2024-09-05 20:20 UTC, closed without merging